_BASE_: "Base-CenterNet.yaml"
MODEL:
  META_ARCHITECTURE: "GTRRCNN"
  CENTERNET:
    USE_DEFORMABLE: True
    NMS_TH_TEST: 0.6
  ROI_HEADS:
    NAME: GTRROIHeads
    PROPOSAL_APPEND_GT: False
    NO_BOX_HEAD: True
  WEIGHTS: 'models/CH_FPN_1x.pth'
  ASSO_ON: True
  ASSO_HEAD:
    NEG_UNMATCHED: True
    ASSO_THRESH: 0.3
    ASSO_THRESH_TEST: 0.55
    ASSO_WEIGHT: 1.0
    NUM_WEIGHT_LAYERS: 0
    NO_POS_EMB: True
SOLVER:
  USE_CUSTOM_SOLVER: True
  MAX_ITER: 8000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00005
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_MULTIPLIER: 0.1
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1280
  NOT_CLAMP_BOX: True
  TEST_INPUT_TYPE: square
  TEST_SIZE: 1560
  VIDEO:
    TRAIN_LEN: 8
    TEST_LEN: 32
VIDEO_INPUT: True
VIDEO_TEST:
  MAX_CENTER_DIST: 1.0
  OVERLAP_THRESH: 0.2
  DECAY_TIME: 0.9
  WITH_IOU: True
  NOT_MULT_THRESH: True
DATASETS:
  TRAIN: ("mot17_halftrain","crowdhuman_amodal_train")
  TEST: ("mot17_halfval",)
FIND_UNUSED_PARAM: True
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  SOURCE_AWARE: True
  DATASET_RATIO: [1, 1]
